name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 패키지 설치
        run: npm ci
      - name: playwright 설치
        run: npx playwright install --with-deps
      - name: 테스트 실행
        run: MOCK=true CI=true SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} SUPABASE_URL=${{ secrets.SUPABASE_URL }} npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
